### ISSUE TITLE
Mag estDuration in createTask van project geen duration zijn ipv. int

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#1]

**Comment by mrTsjolder** [comment]
mag wel, denk ik. De input blijft wel een int...

**Comment by isostorm** [comment]
Ja, mss wel en volgens creation pattern is task verantwoordelijk om een nieuwe duration aan te maken om dat ie em ze beheert, ma mogen de begin en end time dan wel localdatetimes zijn ipv strings? da lijkt nie echt consistent.

**Comment by mrTsjolder** [comment]
de String-object conversie is iets dat typisch in een controller mag gebeuren, denk ik. 
De duration is een beetje dubbelzinniger, maar zou wel geconverteerd mogen worden naar duration als die weet dat een duration nodig is. (maar ik denk wel dat dat hogere koppeling heeft...)

**Comment by isostorm** [comment]
Ja gebt wss gelijk, taak moet duration aanmaken.
