### ISSUE TITLE
Validity of time spans omtrent failed tasks

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#10]
"The time span of different tasks
may overlap, except if they depend on each other (if task B depends on
task A, then A must have a time span that ends before the time span of B
begins)."

Is het voorbeeld hieronder volgens jullie toegelaten? (A en B in het voorbeeld zijn niet dezelfde A en B als in de tekst hierboven)
chronologische volgorde van acties:
1 B aangemaakt
2 A aangemaakt met prerequisite B
3 A = failed, time span toegekend
4 B = finished, time span toegekend
![task_voorbeeld](https://cloud.githubusercontent.com/assets/10974333/6505456/ce5c2b72-c342-11e4-8124-6be2af5a6085.jpg)

**Comment by isostorm** [comment]
Ja volgens mij mag een taak failen als de dependencies nog niet voldaan zijn, ze mag enkel niet finishen, maar door da addendum snap ik lik niets meer vn de timespans van taken.

**Comment by mrTsjolder** [comment]
Dit is gewoon de vraag: is de overgang "unavailable -> failed" toegestaan, of niet?
Ik blijf het nog altijd raar vinden om een taak te laten failen voor ze überhaupt begonnen is, maar bon

**Comment by Xenolel** [comment]
Volgens "4.4 Use Case: Update Task Status" is het niet de bedoeling een unavailable task te kunnen updaten. dus ja kzal da veranderen

**Comment by mrTsjolder** [comment]
Dan kan A nooit failed zijn als B nog niet gestart is (aangezien A pas available wordt als B finished is)

**Comment by Xenolel** [comment]
yup. da voorbeeld was in de veronderstelling dat unavailable->failed wel mogelijk was

**Comment by mrTsjolder** [comment]
case closed, zou ik zeggen :p
