### ISSUE TITLE
bewaren id's

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#11]
Klinkt misschien heel stom, maar zijn containers geen information experts over ID's?
Ik bedoel maar dat een project zijn eigen ID eigenlijk helemaal niet nodig heeft en een project ook niet.

**Comment by isostorm** [comment]
Aan den ene kant ebje gelijk, ma dan moe project ook een map met de keys teruggeven ipv een lijst + taak moet zijn eigen id genereren dus taak is de information expert. Bij projecten kan dit eventueel wel

**Comment by mrTsjolder** [comment]
ik zou het voor taak en project gelijk houden... (moet project ook een eigen id aanmaken?) 
Ik moet daar overgelezen hebben van Task...

**Comment by Xenolel** [comment]
Mogelijkheden:
- project & task generen hun eigen ID
- project manager genereert ID voor aangemaakte project & project genereert ID voor Task (is het nodig dat een task een compleet uniek ID heeft of enkel per project?)
- gebruiker kiest de IDs

De tweede optie is misschien interessant?

**Comment by isostorm** [comment]
Bij project is da al zo. Ma taken moeten wss een uniek id hebben over het volledige programma, bij het inleesbestand is da zo en zo kunnen ook taken uit andere projecten toegevoegd worden aan een project, wat we nu eigenlijk verbeiden ma da is eigenlijk wel handig soms als projecten van elkaar afhangen. + selecteren in available tasks is makkelijker.
