### ISSUE TITLE
Duration getEndtimefrom

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#13]
Duration getEndTimeFrom(begin) houdt momenteel geen rekening met weekends, kan iemand da fixen? Want ik heb het gehad met die tijdzever.

**Comment by mrTsjolder** [comment]
I'm on it...

**Comment by mrTsjolder** [comment]
Is dat niet al allemaal in rekening gebracht door de duration zelf? :)

**Comment by mrTsjolder** [comment]
probleem gevonden (ook wat extra constanten toegevoegd)...

**Comment by isostorm** [comment]
Nu worden enkel het eerste weekend geskipt, als er meerdere weekends tussen zitten, failt het. Die duration is veel gecompliceerder dan daje zou verwachten. Kzou ook niet kiezen voor een variabele werkweek, dat maakt alles nog complexer. Want kan het zijn dat de between constructor nu ook niet meer werkt?

**Comment by mrTsjolder** [comment]
het gaat toch maar over 1 dag en de rest van je duration zijn sowieso werkuren...
ik denk dat de variabele werkweek niet zo veel complexiteit met zich meebrengt...
al uw tests slagen nog, dus als ze goed geschreven zijn, werkt alles nog...

**Comment by isostorm** [comment]
De testen waren te simpele gevallen, keb ze aangepast, het is supercomplex wi met die weekends, Frederic ging der ne keer na kijken.
