### ISSUE TITLE
Lege Strings

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#14]
Er worden lege strings geaccepteerd als naam en description van zowel een project als een taak, fixen!

**Comment by Xenolel** [comment]
gefixed in task

**Comment by mrTsjolder** [comment]
ik zie niet in hoe dat zou kunnen... 
als het gaat over mijn unitTests dan is dat omdat de constructor van Task voortdurend illegalargumentexceptions gooit wegens prereqs die er niet zijn...

**Comment by isostorm** [comment]
Er wordt enkel gechecked of een string niet null is maar niet of hij "" en ik denk nie echt da we willen dat er projecten met een lege naam bestaan. Als we het echt zot maken kunnen we zelf checken of een naam enkel uit spaties bestaat.

**Comment by mrTsjolder** [comment]
zoooooooo......
komt in orde
