### ISSUE TITLE
Task constructor -status

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#15]
Klopt het dat we niet langer willen dat het mogelijk is de status van een task mee te geven in de constructor?

Dit betekent dat de volgende 2 constructors overblijven:
- Task(String description, long estDur, int accDev, Task[] prereq)
- Task(String description, long estDur, int accDev)

**Comment by isostorm** [comment]
We hebben die constructor nog nodig voor het inleesbestand, want sommmige taken staan op finished daar blijkbaar.

**Comment by Xenolel** [comment]
Moeten we daarmee rekening houden? We kunnen ook de taak aanmaken en ze daarna updaten in de parser

**Comment by isostorm** [comment]
Ja inderdaad da kan ook natuurlijk en dat is mss het best, dus ja dan mag die constructor idd weg

**Comment by mrTsjolder** [comment]
nog een voorstel: extra constructor 
Task(String description, long estDur, int accDev, Task altFor, Task[] prereq)
zodat setAlternativeTask() in die constructor kan gebeuren en private wordt?

**Comment by isostorm** [comment]
Ja dat is een zeer goed idee

**Comment by Xenolel** [comment]
Als je setAlternativeTask op private wilt zetten, betekent het ook dat je niet langer bestaande taken kunt kiezen als alternative voor een andere taak

**Comment by mrTsjolder** [comment]
misschien is het niet slecht als we die abstractie maken... ?

**Comment by Xenolel** [comment]
sgoed, kzal setAlternativeTask private maken
