### ISSUE TITLE
creators

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#16]
Omdat losse taken in onze oplossing momenteel niet kunnen bestaan, moeten ze gecreëerd worden door Project. Het probleem met deze aanpak is dat ik bijna niets meer kan testen (@isostorm). Laten we de creators dan de objecten teruggeven of testen we gewoon heel vaag.
PS: hetzelfde zou dan moeten gelden voor een Project, want een project kan niet testen of zijn id uniek is...

**Comment by isostorm** [comment]
Ik zou de creators idd het object laten teruggeven dat ze gecreëerd hebben, in het inleesbestand is dit feitelijk ook nodig. En eigenlijk kun je hiervoor wss ook mocking objects gebruiken :p

**Comment by mrTsjolder** [comment]
geven we dan een object terug of bv enkel de id? 
PS: wat met projects?

**Comment by isostorm** [comment]
Ik zou een object teruggeven, want het is toch de bedoeling anders om met id het object dan toch op te vragen. En bij projecten doen we mss best hetzelfde gedrag, ge moogt het ook aanpassen.

**Comment by mrTsjolder** [comment]
okay, ik kijk ervoor
