### ISSUE TITLE
moet Task.getStatus() private zijn?

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#18]
`public boolean isFinished() // TODO waarom is dit nodig?`
-> @mrTsjolder
`public boolean isFinished() // TODO daarom is dit nodig.`
Moet getStatus private gemaakt worden en vervangen worden door isAvailable, isFinished, isFailed, en isUnavailable?

**Comment by mrTsjolder** [comment]
ik denk dat de isFinished het enige is dat echt nodig is (in de vorm dat het nu gedefinieerd is)
de available check wil ik nog wel in project nemen... :)

**Comment by Xenolel** [comment]
Task.isAvailable werkt nu
