### ISSUE TITLE
constructor Duration verkeerd gebruikt

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#20]
constructor voor Duration verkeerd gebruikt in task

nood aan constructor Duration(int hours, int minutes)?
ik maak hem alvast aan...

**Comment by isostorm** [comment]
Ah mss wel, waar wordt da verkeerd gebruikt juist?

**Comment by mrTsjolder** [comment]
het wordt blijkbaar niet verkeerd gebruikt (behalve door mij), maar waar wordt de conversie van de uren en minuten naar minuten gemaakt? 
lijkt mij de verantwoordelijkheid voor duration...

**Comment by mrTsjolder** [comment]
voorstel om estDurHours en estDurMinutes door te geven tot aan duration

**Comment by isostorm** [comment]
Hoe bedoel je? Duration gebruikt als interne representatie minuten ma da kan volgende keer veranderen na milliseconden, de gebruiker moe da niets van weten toch?

**Comment by mrTsjolder** [comment]
inderdaad, maar de gebruiker moet 'estimated duration' in uren en minuten kunnen ingeven, terwijl overal gewoon een int/long wordt doorgegeven.
Mijn voorstel is dus om van estimated duration twee variabelen te maken en in een constructor Duration(int hours, int minutes) pas de conversie te doen...

**Comment by isostorm** [comment]
Ah momenteel moet de gebruiker gwn minuten ingeven. Dus kzou da voorlopig zo laten, want der zijn nog genoeg andere dingen die nie naar behoren werken.
