### ISSUE TITLE
updateTask()

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#21]
ik kan een alternatief voor een gefailde task updaten met dezelfde starttijd als de gefailde task zelf. Is dit een probleem?

**Comment by Xenolel** [comment]
Gezien we hebben beslist het enkel mogelijk te maken een taak toe te kennen als alternative voor een andere taak bij zijn creatie, moet de starttijd van de alternative task na de eindtijd van de failed task zijn. Ik zal het aanpassen

**Comment by Xenolel** [comment]
Oh ik besef net dat dit niet kan gechecked worden in de alternatieve task omdat deze niet weet waarvoor hij alternatief is

**Comment by Xenolel** [comment]
Misschien is het toch beter niet de design beslissing te nemen dat een taak enkel kan toegekend worden als alternative taak voor een andere bij zijn creatie en dus opnieuw setAlternativeTask public te maken. Dan is er geen probleem

**Comment by Xenolel** [comment]
alternativeTask.update kan niet checken of de time spans overlappen gezien deze niet weet waarvoor hij alternatief is.

Als we beslissen om setAlternativeTask weer public te maken en dus een bestaande taak te kunnen zetten als alternative task voor een failed task, is er geen probleem. Is het goed als we het zo doen?

**Comment by Xenolel** [comment]
Mogelijkheden:
- setAlternativeTask private

_?Probleem?_: wanneer alternativeTask.update() opgeroepen wordt, kan alternativeTask niet checken of de gegeven time span na de time span is van de task waar hij toe hoort
- setAlternativeTask public

_Probleem_: task kan niet checken of de gegeven alternativeTask wel tot hetzelfde project hoort

**Comment by mrTsjolder** [comment]
Extra mogelijkheid: Task houdt bij waarvoor hij een alternatief is
gevolgen:
- setAlternativeTask niet meer nodig (zoals ze nu bestaat)
- constructor kan alles controleren
- dependencies worden doorgegeven aan de alternatieve taak (zie example scenario in de opgave)
- de gefailde taak wordt volledig onbelangrijk in het project en zorgt niet meer voor problemen (enkel opletten voor de tijd die nodig was)
- een alternatief voor een taak kan niet gecreëerd worden voor de oorspronkelijke taak gefailed is
- ...

de tweede mogelijkheid lijkt mij iets beter (dat probleem is uiteindelijk toch de verantwoordelijkheid voor Project)

**Comment by isostorm** [comment]
Ik ben niet zo bekend met de problematiek van taak maar als alles zo is opgelost is dit goed voor mij, als later dit alternatief moet kunnen gewijzigd worden zitten we dan wel met een probleem, maarja.

**Comment by Xenolel** [comment]
Gevolgen extra mogelijkheid:
- Een taak kan meerdere alternatieven hebben (misschien is dit wel positief?)
- Alternatieve taken zijn verantwoordelijk voor de isFulfilled status te updaten van hun alternativeFor taak
- Een taak kan niet meer schatten wanneer hij ten vroegste fulfilled zal zijn omdat hij niet weet wat zijn alternatief is

Dit laatste punt is denk ik een probleem?

Over de tweede mogelijkheid:
_"This means that the client of the public interface of a class cannot bring the objects of that class, or objects of connected classes, in an inconsistent state."_
Het probleem met de tweede mogelijkheid is dat dit niet defensief programmeren is omdat het mogelijk is taken van verschillende projecten te verbinden terwijl we dit niet willen.

**Comment by Xenolel** [comment]
Ohh kheb denk ik een oplossing, wat als de we de modifier "public" van setAlternativeTask weg doen, daardoor  kunnen enkel klassen in ons package de methode oproepen en is alles in orde en kunnen we verzekeren dat enkel project de methode gebruikt

Ik denk dat het nodig is dat we eens bewust nadenken over wat de modifier moet zijn van iedere methode.

**Comment by isostorm** [comment]
ja en maak de constructor van task ook maar alleen package visible en van project

**Comment by isostorm** [comment]
Maar alhoewel, er sta wel de client van de public interface da kan even goe een klasse zijn uit da package toch?

**Comment by Xenolel** [comment]
hmm kdenk het niet, kdenk dat public interface enkel gaat over de methodes/variabelen die werkelijk de _public_ modifier hebben

**Comment by isostorm** [comment]
ja voor mij is dit in orde dan. Update van taak moet ook passeren langs project  dus da moet dan ook public weggehaald worden?

**Comment by Xenolel** [comment]
Ja idd, kben momenteel bezig alle task modifiers zo restrictief mogelijk te maken. (behalve getters)

**Comment by Xenolel** [comment]
Als de task constructor enkel package visible is dan kan die niet meer getest worden.
We willen echter wel dat die enkel package visible is omdat een task altijd tot een project moet horen

**Comment by isostorm** [comment]
Ja normaal zaten de tests in het zelfde package als het domain, maar in een andere folder, maar in Eclipse gaf dat blijkbaar errors -.-

**Comment by mrTsjolder** [comment]
dat is dan toch niet hetzelfde package? o.O
Het lijkt mij overbodig om alles package visible te maken. Als we aannemen dat een ongekoppelde task ook toegelaten is, komt het systeem namelijk niet in een verboden toestand...
Dat lijkt mij geen probleem...

**Comment by isostorm** [comment]
Ge kunt wel src/domain en test/domain hebben, da is wel hetzelfde package, allé in netbeans toch. Ja maar tis idd niet echt een probleem, laat het maar zo.

**Comment by Xenolel** [comment]
maar er is een constructor in task met _Task alternativeFor_ waardoor de toestand toch weer invalid zou kunnen zijn?

Zo zou een losse taak kunnen verbonden zijn met een taak in een project

**Comment by isostorm** [comment]
Wrm is die constructor er?

**Comment by Xenolel** [comment]
Is niet per se nodig maar werd gevraagd aan te maken, maar sowieso geldt dat dit ook mogelijk is met het argument _prerequisiteTasks_

**Comment by mrTsjolder** [comment]
omdat ik nu nog altijd die setAlternativeTask() gebruik en ik denk (nog altijd) dat dat eigenlijk een verantwoordelijkheid is voor Task...

**Comment by mrTsjolder** [comment]
eigenlijk (en het spijt me dat ik elke 2 stappen van gedacht verander) zou het het beste zijn als je 1 constructor hebt en een aantal constanten om aan te geven wat geen alternative en geen prerequisite betekenen...

**Comment by Xenolel** [comment]
wat zouden die constanten dan kunnen zijn? behalve null?

**Comment by isostorm** [comment]
Die setAlternativeTask()  is de juiste methode, Frederic heeft aangegeven wat de problemen zijn als dit weggaat, tenzij dit kan opgelost worden, maar ik vrees ervoor. Die constructors mogen eigenlijk niet aangeroepen worden, want we laten geen losse taken toe. Ge moe da probleem met Eclipse ma fixen.

**Comment by isostorm** [comment]
@Xenolel die constanten moeten gwn verbergen wa daje gij gebruikt als default, mss is da beter dan telescoping

**Comment by Xenolel** [comment]
ma ksnap niet wat Task.noAlternativeTask zou kunnen zijn?

**Comment by isostorm** [comment]
gwn null lik daje zegt + vergeet nie da publieke constanten ook commentaar nodig hebben.

**Comment by Xenolel** [comment]
en ja kdenk daje gelijk hebt dat die tests in hetzelfde package moeten zitten, tis nu wel efkes irritant met eclipse :/

**Comment by mrTsjolder** [comment]
ik snap het punt nie
bij package-visible constructors, kan nog altijd ergens iemand de constructor oproepen, die dat eigenlijk niet mag doen...
De enige manier om een Task echt existentieel te laten afhangen van een project is om elke task een project te laten bijhouden. Dan stel ik wel voor om de link van project naar id te wissen en een lekker incohesive design te maken...

**Comment by Xenolel** [comment]
ma die persoon maakt dan toch niet enkel gebruik van de public interface? dit moet toch niet meer beschermd worden door defensive programming?

**Comment by isostorm** [comment]
Ja en dan kunnen gasten zoals controllers al niets meer verkeerd doen.
