### ISSUE TITLE
project en duration niet de beste vriendjes, blijkbaar

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#23]
in mijn methode isOnTime() zit ik met het probleem dat creation time en due time van een project niet in een werkweek vallen en bijgevolg problemen geven als ik de methode getEndTimeFrom() wil gebruiken...

de vraag is nu of creation time en end time in de werkweek moeten vallen (TimeSpan kan dat dan controleren) OF kan er iets aangepast worden in getEndTimeFrom()?

**Comment by Xenolel** [comment]
in getEndTimeFrom zou je bv kunnen checken of begin niet valid is en indien dit zo is, begin op het dichtste moment zetten dat wel geldig is.
Een andere optie is calculateNearestWorkTime(LocalDateTime) maken en dit dan doorgeven aan getEndTimeFrom

Anderzijds zou het wel logisch zijn dat de creation time & end time in de werkweek moeten vallen

**Comment by mrTsjolder** [comment]
als begin time niet during worktime is, wordt de eerstvolgende worktime gezocht met een nieuwe, geteste methode.
Dit heeft al mijn problemen opgelost :)
