### ISSUE TITLE
Wat we niet mogen vergeten!

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#24]
We moeten vrijdag indienen voor 18:00u

To do:
- ~~code afwerken~~
  - ~~overdue tasks~~
  - ~~total execution time project~~
  - ~~task update timespan na project creationtime~~
- ~~scenariotests, daar ben ik aan bezig voor showProjects en UpdateTask~~.
- ~~public variabelen hebben ook commentaar nodig~~
- doc genereren
- jar genereren
- UML-diagramma's in orde brengen
- beslissen wie de zip doorstuurt
- ~~tijd veranderen naar juiste formaat~~
- ~~project meegeven aan setAlternative & update~~
- ~~constructors met alternative weg doen~~
- ~~protected maken van update & constructors~~
- diagrammen: isonTime, getDelay, voor elke use case + mss ook createTask, das ook nog speciaal

Daarnaast (maar niet per se tegen vrijdag, denk ik) zou best ook nog het volgende gebeuren:
- tests een beetje verbeteren voor sommige dingen (zal later werk vereenvoudigen)
- presentatie knutselen
- fantaseren over eventuele addenda:
  - Terugkerende taken
  - Subtaken
  - Taken prioriteiten/labels geven
  - Taken/projecten later nog aanpassen

PS: ook de peer-assessment niet vergeten

**Comment by isostorm** [comment]
- scenariotests, daar ben ik aan bezig voor showProjects en UpdateTask.

Moeten we nog vragen stellen aan Mario?

**Comment by mrTsjolder** [comment]
moeten alleszins niet, maar als er nog vragen zijn, zouden we ons beter haasten...

**Comment by isostorm** [comment]
Kweenie of er nog problemen met die overdue bvb verschil tussen unacceptably overdue en overdue ,zullen optreden, want da is nog nie geïmplementeerd zekr?

**Comment by mrTsjolder** [comment]
neen, omdat ik er niet aan uit geraak 
en ook omdat getEndTimeFrom() in Duration mijn tests weer naar de ruk helpt :p

**Comment by isostorm** [comment]
wrm? btw keb uw comment proberen aan de passen ma mijn markdown skills zijn nie zot genoeg :p

**Comment by mrTsjolder** [comment]
getEndTimeFrom() is gefixed en het probleem is dat ik mij niet zo goed kan concentreren de laatste tijd...

**Comment by isostorm** [comment]
mss moeten we toch opteren voor mock objecten, zo dat de testen niet zo afhankelijk zijn van andere componenten, maar gezien de testen toch niet moeten ingediend worden zou ik er momenteel niet te heel veel werk insteken, gwn zorgen da ze testen of uw implementatie werkt. btw getTotalDelay moet 0 teruggeven als duration als het op tijd is, kzal da aanpassen hé.

**Comment by Xenolel** [comment]
Probleem: unavailable tasks worden niet getoond in de gui en kunnen dus niet op failed gezet worden.
Kheb het toegevoegd aan de todos bovenaan

**Comment by Xenolel** [comment]
Probleem:

We willen setAlternativeTask(altTask, project) hebben en in deze methode hetvolgende checken:

    project.hasTask(this) && project.hasTask(altTask)

Dit heeft als gevolg dat de volgorde van de volgende 2 regels in Project.createTask als volgt moet zijn:

    addTask(t);
    if(altFor != Project.NO_ALTERNATIVE)
        getTask(altFor).setAlternativeTask(t, this);

Het probleem is nu dat de task kan aangemaakt worden zelfs als de alternativeFor koppeling mislukt

**Comment by isostorm** [comment]
Het probleem is dat er duidelijk in de opgave sta da enkel de available taken mogen opgelijst worden.

**Comment by Xenolel** [comment]
oh juist :/ ghebt gelijk, beter gewoon azo laten dan
