### ISSUE TITLE
Scenario test

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#25]
Ik heb een scenariotest gemaakt, is dit wat er van een scenariotest verwacht wordt, of sla ik de plank mis?

**Comment by Xenolel** [comment]
ah kdacht al daje vergeten was te pushen :P 
kdenk inderdaad dat het zoiets moet zijn. ik zou niet weten hoe je anders een use case kan testen

**Comment by Xenolel** [comment]
btw kben momenteel bezig met create project scenario test (kzeg et gewoon zoda we geen dubbel werk doen)
