### ISSUE TITLE
Parameter "project" in Task.update

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#27]
De bedoeling van de _project_ parameter in _Task.update(start, end, status, project)_ was dat dan kan gechecked worden of de task in dat project zit en of _start_ na project.getCreationTime() valt. Maar momenteel wordt deze laatste check al gedaan in project.

Mis ik iets of is er toch geen nood aan deze parameter?

Of is de bedoeling van deze parameter dat de toestand van taken/projecten nog beter beschermd is tegen oproepen van Task.Update in ons package?

**Comment by mrTsjolder** [comment]
strikt genomen is die parameter er om ervoor te zorgen dat een task niet geupdate kan worden met willekeurige waarden...
