### ISSUE TITLE
omtrent Task.setAlternativeTask

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#28]
We willen `Task.setAlternativeTask(altTask, project)` hebben en in deze methode hetvolgende checken:

```
project.hasTask(this) && project.hasTask(altTask)
```

Dit heeft als gevolg dat de volgorde van de volgende regels in `Project.createTask` als volgt moet zijn:

```
addTask(t);
if(altFor != Project.NO_ALTERNATIVE)
    getTask(altFor).setAlternativeTask(t, this);
```

Het probleem is nu dat de task kan aangemaakt worden zelfs als de alternativeFor koppeling mislukt

oplossingen:
- `Project.createTask` moet eerst controleren dat `setAlternativeTask` mogelijk is
- exception opvangen, task verwijderen uit project, exception opnieuw gooien

nu weet ik niet echt wat de beste oplossing is

**Comment by isostorm** [comment]
Het 2de lijkt het best ma dan is er wss wel een dubbele check? Wrm mag die taak eigenlijk niet toegevoegd worden, het systeem wordt eigenlijk niet in een verkeerde staat gebracht hé.

**Comment by Xenolel** [comment]
ja we kunnen da inderdaad eigl. gewoon toelaten

**Comment by isostorm** [comment]
Het moet gwn duidelijk vermeld staan in de commentaar.
