### ISSUE TITLE
Duration overbodige methode?

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#29]
public static long getWorkDaysBetween(LocalDateTime begin, LocalDateTime end)
Is overbodig geworden en mag verwijderd worden zekr? Want ze verlaagd de test coverage.

**Comment by Xenolel** [comment]
ja idd, best verwijderen

**Comment by isostorm** [comment]
Jammer, et was nochtans een mooie methode :'(

**Comment by Xenolel** [comment]
rip getWorkDaysBetween
