### ISSUE TITLE
Front controller

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#3]
Hoe gaat de frontcontroller werken?

**Comment by mrTsjolder** [comment]
is dat de controller met de main?

**Comment by isostorm** [comment]
Wat is main?

**Comment by mrTsjolder** [comment]
public static void main(String[] args) {
...
}
De controller die alles moet initialiseren?

**Comment by isostorm** [comment]
Is da nog nie een aparte klasse, want de controller moe anders zichzelf injecteren in het start frame? En ge moet ook het systeem kunnen initialiseren mbv een file. De frontcontroller is eigenlijk gwn een factory vo de handlers momenteel.

**Comment by mrTsjolder** [comment]
ik zou daar ineens de startup aan verbinden, anders is da precies zo nutteloos...
