### ISSUE TITLE
canHaveAsTask(Task t) in Project

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#30]
methode kan niet controleren of de taak in een ander project zit.
(Bidirectionele lijkt zich op te dringen, maar kunnen we dit a.u.b. uitstellen tot volgende iteratie en dit nu gewoon toelaten?)

**Comment by isostorm** [comment]
Dit lijkt me voorlopig idd nog geen probleem, ik zie niet in wrm taken niet tot verschillende projecten mogen behoren.
