### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#31]
Sorry voor de Eclipse gebruikers maar keb de tests verzet voor de javadoc te kunnen genereren, ge moogt ze terugzetten als je wil. Ma de documentatie zal wss nog opnieuw gegenereerd moeten worden als er dingen veranderd worden.

Let op dat javadoc html gebruikt dus > wordt &amp;gt; en & wordt &amp;amp; anders failt ie.
Het staat trouwens op dropbox.

**Comment by mrTsjolder** [comment]
eclipse errort al niet meer op de package-namen, maar ge hebt wel TaskTest verwijderd...
PS: waarom moesten die tests daarvoor verplaatst worden?

**Comment by isostorm** [comment]
Ahja et was blijkbaar niet gecommited. En da was nodig omdat anders tasktest in het domain package als commentaar zou zitten en testen moeten nie in da doc staan zekr? + Mijn test libraries staan apart van mij source libraries dus ie kende Junit nie in domain en da gaf geelsan errors.
