### ISSUE TITLE
String naar LocalDateTime conversie

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#32]
Moet deze conversie gebeuren in de handler of de UI? Want omgekeerd zet de UI bevoorbeeld de eindtijd enzo van bvb. taken ook al om van LocalDateTime naar String, dus het lijkt dan consistenter om het bovengenoemde ook in de UI te doen. Die beslist dan de representatie van de data?

**Comment by Xenolel** [comment]
ja kdenk dat UI dat mag doen, tis geen logica, gewoon representatie

**Comment by mrTsjolder** [comment]
voor mij lijkt dit ook het beste
