### ISSUE TITLE
Iteratie 2 voortgang

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#33]
Dus dit is de voorlopige mail naar Mario, als jullie hem zouden kunnen aanvullen/verbeteren:

Dear Mario

While designing for iteration 2, we have encountered a few issues that we'd like to get an answer to. Because of logistical issues (Pieter-Jan is abroad), we wondered whether it would be possible for you to answer/guide us in the right direction in reply.:
1) Is it right to assume a user can be a manager and a developer at the same time?
2) What can be the issues with aggregating all instances of a class in a static list, for example to keep track of all project instances in the project class itself?
3) For the state pattern should a method like isAvailable() be impelemented in the state classes and only return true in the available class, or is it better to check in Task wheter the current state is an instance of Available?

Kind regards

Dan zou ik ook graag een deadline afspreken, zoals bvb. volgende week woensdag waneer we al een basis moeten hebben en de opgetreden problemen kunnen bespreken.

En zou iedereen hieronder kunnen zetten aan wat hij werkt om een overzicht te bewaren?

**Comment by isostorm** [comment]
Ik werk aan het user systeem dat normaal klaar is, maar er is wel nog ruimte voor verbetering.

**Comment by mrTsjolder** [comment]
ter verbetering:
1. While designing for iteration 2, we have encountered a few issues that we'd like to get an answer to. Because of logistical issues (Pieter-Jan left the country), we wondered whether it would be possible for you to answer/guide us in the right direction in reply.
2. ik zou ook alles in 1 taal doen...

mijn plan:
ik probeer door het bos de bomen te onderscheiden om de resources (proper) in het project te krijgen...

**Comment by isostorm** [comment]
Lol ja ma da nederlands komt uit vragenaanmario.txt, ma kweet nie wat bedoelt wordt, Frederic heeft da geschreven. 
En kun je de sequence diagrams gebruiken voor die resources of zije volledig anders bezig?
Als je over iets twijfelt moeje et ma hier zetten hé, we kunnen dan ook meedenken.

**Comment by mrTsjolder** [comment]
die sequence diagrams zouden misschien wel handig zijn...
Ik heb het eens op een andere manier geprobeerd, maar het lijkt niet echt zijn vruchten af te werpen...

**Comment by isostorm** [comment]
Kzie dat ze nie allemaal op dropbox staan allemaal, Frederic moe ze der nog opzetten wss, ma als we iets concreter hebben kunnen we ook vragen stellen aan mario. Want momenteel ist lik nog niet de moeite om een mail te sturen.

**Comment by mrTsjolder** [comment]
Dit is wat ik had, maar dit zijn enkel dependencies en het lukt mij niet om de dependencies zo te schikken dat alles mogelijk is.... (bovenaan staat Task)
![screen shot 2015-04-10 at 19 37 37](https://cloud.githubusercontent.com/assets/3738082/7093418/497fc9b6-dfb9-11e4-95b8-0c6ab6ba66c6.png)

**Comment by isostorm** [comment]
Als taak zijn reservations bijhoudt ist moeilijk om conflicterende reservaties op te sporen zeker? Wa zou die mediator juist doen?

**Comment by mrTsjolder** [comment]
de mediator houdt alles bij en verzorgt alle communicatie tussen de verschillende klassen

**Comment by Xenolel** [comment]
sry alles staat nu op dropbox

Die derde vraag is eigenlijk nie zo belangrijk. Tis gewoon omdat als je de available tasks wil verzamelen, je dan moet checken of task.getState() van het type Available is. Terwijl dit iets is dat we eerder proberen te vermijden in het state pattern.

Kweet niet echt goed wat ik moet doen, ik kan anders ten eerste keer kijken naar de tests die momenteel failen en die fixen, ook kan'k de code keer helemaal overlopen. Behalve dat resteert er nog de executing state en die simulation die moeten gedaan worden zeker?

**Comment by isostorm** [comment]
Klopt en die canhaveastimespan moet ook nog weggewerkt worden, dan verdwijnt die isfulfilledbefore ook. Want zoals dak et nu zie is die enkel relevant om van available na finished of failed te gaan? Ma als die canhaveastimespan nie weg kan moe die isfulfilledbefore zeker weg.   

Ma die executing state is afhankelijk van de resources, dus da moet eerst uitgeklaard worden, zo rap mogelijk, desnoods moeten we een Skype meeting houden.

**Comment by isostorm** [comment]
Zo de mail is verzonden naar Mario, en woensdag komen we op Skype om de voortgang te bespreken?

**Comment by Xenolel** [comment]
voor mij is da goed
