### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#35]
Voorstel: Resources kunnen over lange tijden gereserveerd worden, onafhankelijk van hun fysieke beschikbaarheid. bvb: auto is beschikbaar van 9 tot 10 uur op werkdagen, maar ik reserveer hem van 8u 1 april tot 14u 6 maart.
- alle resources hebben een workweekconfiguration die enkel gebruikt wordt om de beschikbaarheid op het moment dat de taak naar executing gaat te controleren en gebruikt wordt om de estimated end time van een taak te berekenen.

Dit laatste wordt bereikt door de workweekconfiguration van de minst beschikbare resource te gebruiken. 

bedenkingen?

**Comment by mrTsjolder** [comment]
Ik heb toch het gevoel dat die configuration in het type thuis hoort...
Dit zou een bi-directionele relatie kunnen vereisen, maar als het moet dan moet het... :p

**Comment by mrTsjolder** [comment]
mogen resources gereserveerd worden door een taak die geen resources van dat type nodig heeft?

**Comment by Xenolel** [comment]
ik zou da toelaten, er kunnen bv resources zijn die een taak vergemakkelijken ma niet required zijn

**Comment by isostorm** [comment]
Ja Frederic heeft gelijk en oe meer constraints dat we uitvinden, oe moeilijker we het ons zelf maken. 

En ja der moe lik een mogelijkheid zijn om een standaardtype configuration te hebben die eventueel kan aangepast worden voor specifieke resources zoals bij developers.
