### ISSUE TITLE
task.nextAvailableStartingTimes(LocalDateTime from)

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#36]
Als ik de methode oproep krijg ik: 
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
    at java.util.TreeMap.key(TreeMap.java:1323)
    at java.util.TreeMap.lastKey(TreeMap.java:297)
    at java.util.TreeSet.last(TreeSet.java:401)
    at domain.Task.nextAvailableStartingTimes(Task.java:713)

Bij andere taken krijg ik deze error niet, maar ook geen starttijden
Kweenie hoe dit komt?

**Comment by mrTsjolder** [comment]
Dit komt omdat de set waarop last() wordt opgeroepen leeg is...
Dit zou kunnen opgelost worden met:

```
if(result.isEmpty())
    result = temp;
```

maar het plan was om result te initialiseren met de beschikbare tijden van de developers...

**Comment by isostorm** [comment]
Tenzij daje van developer ook een requiredresourcetype maakt da iedere taak standaard heeft?
Want taak heeft minimum 1 developer nodig om na executing te gaan.

**Comment by mrTsjolder** [comment]
Inderdaad, maar normaal zou da lijntje die error moeten fixen, want vanaf dan moet er altijd iets in zitten...

**Comment by isostorm** [comment]
Ok cva ma gaan we da nu zo doen met die developers?

**Comment by mrTsjolder** [comment]
ik weet eigenlijk eventjes helemaal niet meer wat er allemaal aan het gebeuren is...
Het is in elk geval mogelijk, maar wat zijn de alternatieven?

**Comment by isostorm** [comment]
De alternatieven zijn daje developers en resources effectief apart behandeld, ma da is lik zo belachelijk, want ze zijn in principe gelijk

**Comment by mrTsjolder** [comment]
Overerving lijkt mij inderdaad een goeie oplossing te zijn, maar is het nodig dat ze een type hebben?
Ik blijf voorstander van een aparte lijst van developers, want developers zijn sowieso required, terwijl andere types niet required zijn.

**Comment by isostorm** [comment]
Ma daar geef je ook de reden waarom dat zo gepast is, developers kunnen gwn standaard in de requirements van een taak zitten met een minimale quantiteit van 1. + In de UI moek op 1 of andere manier aan de lijst van developers geraken en als ze een resourcetype zijn is da makkelijk en uniformer
