### ISSUE TITLE
Resourcetype

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#37]
In de userinterface kan de gebruiker een bepaalde detailedresource selecteren. Hoe zet ik die terug om naar een echte resource. Om het id te kunnen gebruiken, moet ik ook het resourcetype hebben.

**Comment by mrTsjolder** [comment]
Ik zou zeggen met behulp van het id.
Ik versta het probleem niet helemaal, vrees ik...

**Comment by isostorm** [comment]
Ok ik heb het id maar aan wie vraag ik de resource instance?

Btw bij planning geef je een lijst van resources op, hoe controleer je da die lijst voldoet aan de requirements van een taak?

In beide gevallen moeje lik toegang ebben tot de resourcetype?

**Comment by mrTsjolder** [comment]
Idee: in de database vind je alle resourcetypes. Misschien kan je daar ook een methode maken die alle resources terug geeft...

Voor die planning ben ik het momenteel even kwijt. Twee mogelijke oplossingen zouden kunnen zijn:
1. Bi-directionele relatie tussen resource en resource type
2. Methode in resource `public boolean isOfType(ResourceType type)`

**Comment by isostorm** [comment]
En kzal et dan zo dan met die db.

ja kpeis dat eerste beter is, zodawe in resource een method canWorktoghether(List<Resource>) kunnen hebben ofzo

**Comment by mrTsjolder** [comment]
wa zou die `canWorkTogether` methode dan wel doen?

**Comment by isostorm** [comment]
hetzelfde als canhaveascombination in resourcetype ma dan met effectieve resources

**Comment by mrTsjolder** [comment]
waarvoor zou dat dan nuttig zijn?
Als de checks gedaan worden bij initialisatie van die requirements, is die methode volledig zinloos...

**Comment by isostorm** [comment]
Aja idd gebt gelijk sorry, kwas effkes verkeerd. We moeten idd gwn weten van welk type een resource is en tellen of we der genoeg hebben.
