### ISSUE TITLE
Todo lijst iteratie 2

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#38]
We moeten vrijdag indienen voor 18:00u

To do:
- code afwerken
  - planning
  - Individuele lunchbreak developers
  - Overgaan naar executing, hangt af van planning
  - 8 TODO's
- scenariotests voor plantask i.c.m. resolveconflict.
-  doc genereren
- jar genereren
- UML-diagramma's genereren
  - bvb. plan task
  - bvb. execute task
  - ...
-  beslissen wie de zip doorstuurt

Daarnaast (maar niet per se tegen vrijdag, denk ik) zou best ook nog het volgende gebeuren:
- tests een beetje verbeteren voor sommige dingen (zal later werk vereenvoudigen)
- presentatie knutselen
- fantaseren over eventuele addenda:
  - Terugkerende taken
  - Subtaken
  - Taken prioriteiten/labels geven
  - Taken/projecten later nog aanpassen

PS: ook de peer-assessment niet vergeten

**Comment by Xenolel** [comment]
~~planning memento~~
~~Task.setPlanning in PlanTaskCommand~~

~~Task.isFulfilledBefore aanmaken en delegeren naar~~
~~Task en status enzo in aparte package~~

Task.canHaveAsPrerequisiteTasks moet checken of ze tot dezelfde project behoren
Project.canHaveAsTask logica verplaatsen naar Task

Alle resources krijgen een workweek configurations
    -> voordat een taak naar executing gaat, checken of ze available zijn
    -> Resouce.isAvailable checkt gewoon of het in available is voor de workweek configuration

Planning wordt clock observer en verwijderd zichzelf uit een taak wanneer nodig

tijd over: lunchbreak verzetten
