### ISSUE TITLE
Planning object?

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#39]
Misschien is het toch inderdaad beter een planning object te hebben die de reservation en het planningsinterval bijhoudt ofzo? Want nu moeten we de reservation van een taak lik via een omweg via resourcetype gaan zoeken.

Der zit trouwens een fout in plantaskcommand door mijn schuld, ie annuleert de reservations van de opgegeven resources, ma da zijn nie persé dezelfde lik die daje de vorige keer ebt gereserveerd. Met da planning object zouje makkelijk de huidige reservaties kunnen annuleren.

**Comment by Xenolel** [comment]
bedoel je dan dat een reservation een task en een resource bijhoudt? en ook nog een time span?
