### ISSUE TITLE
user interface: selectie van required resource types in use case 'Create Task'

### ISSUE THREAD

**Issue by Xenolel** [mrTsjolder/SWOP-KULAK#40]
white board wordt simpelweg genegeerd omdat de lijn niet geselecteerd is:
![screenshot 2015-05-11 00 08 35](https://cloud.githubusercontent.com/assets/10974333/7556482/1527382c-f772-11e4-8d8a-014eea9a1e8c.png)
zowel white board als demo kit worden toegevoegd aan de taak:
![screenshot 2015-05-11 00 08 39](https://cloud.githubusercontent.com/assets/10974333/7556483/17b54bce-f772-11e4-9bdf-b91820399858.png)

**Comment by isostorm** [comment]
Keb direct wa andere UI bugs gefixed ook
- Keb gemaakt dat ie enkel na de nummers kijkt en nie naar de selectie.
- Keb de naam uneditable gemaakt
- Plan task toont nu ook de estimated duration in minuten
- lunchbreak cancel button is gefixed
- En de simulation bug voor gewone gebruikers is ook gefixed

**Comment by mrTsjolder** [comment]
is dit nu opgelost? 
1. Ja: close
2. Neen: mergen bij TODOs
