### ISSUE TITLE
plantTaskHandler.getDevelopers()

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#45]
Deze methode is overbodig?

**Comment by mrTsjolder** [comment]
neen, ik ging dat nog veranderen in de UI, maar dit is iets wat moet aangeboden worden in de handler i.p.v. zelf uitgezocht in de GUI volgens mij...

**Comment by isostorm** [comment]
Da was vroeger apart. Ma is da nu nog belangrijk daje da apart kunt aanduiden, want devs zijn eigenlijk exact hetzelfde als resources. Zeker nu daze een quantity requirement hebben.

Op 21-mei-2015 17:02 schreef mrTsjolder notifications@github.com:
neen, ik ging dat nog veranderen in de UI, maar dit is iets wat moet aangeboden worden in de handler i.p.v. zelf uitgezocht in de GUI volgens mij...

---

**Comment by mrTsjolder** [comment]
in het systeem is dat misschien zo, maar de UI zou daardoor niet veranderd mogen worden in mijn ogen... Als je het liever zo houdt, mag je zelf iets uitvinden in plantaskscenariotest voor step 8 en die methode verwijderen
