### ISSUE TITLE
Fixen tests

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#46]
alle tests zijn gefixed, maar er was nog iets met de UI in showProjectsHandler:
Je kan niet zien tot welke branchoffice een project behoort...
Je kan van een taak de requiredResources niet zien...
(vind ik persoonlijk behoorlijk vervelend)

**Comment by isostorm** [comment]
Werk unplanned execution? + die required resources gaak fixen

**Comment by mrTsjolder** [comment]
unplanned execution wordt nu gewoon gedaan met de resources van de planning, dus dat werkt zolang die resources available zijn...

**Comment by isostorm** [comment]
aja cva, want resourcetypes kunnen toch nie gereserveerd worden bij ons. En nu ist mogelijk om de required resources te zien.

**Comment by mrTsjolder** [comment]
het zijn de specifieke resources van de planning, maar whatever

**Comment by isostorm** [comment]
ah da was al zichtbaar
