### ISSUE TITLE
Project is finished

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#5]
Gebeurt de check of een project finished is on-the-fly of met flag?

**Comment by mrTsjolder** [comment]
Nu is het nog met flag, maar ik heb zitten denken en de enige reden waarom ik die flag nodig heb, is om performance redenen (het is te dom om de hele tijd te blijven checken als hij al finished is)
ik zou dus zonder vlag werken en daar gewoon een methode van maken die controleert of alle taken finished zijn.
