### ISSUE TITLE
Available tasks

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#6]
Kan Task geen statische lijst van alle taken die gecreërd worden aggregeren, dit zou getAvailable tasks sterk versimpelen, maar dan moet task wel een pointer hebben naar zijn project. Wat wss toch nodig is voor alternative task?

**Comment by mrTsjolder** [comment]
ik denk dat we op die manier alle GRASP principes uit het oog verliezen...
We moeten het design echt nog eens grondig bekijken, want met al die bi-directionele dingen zullen we niet ver geraken. Ik zal mij deze middag eens op onze diagrama's storten

**Comment by Xenolel** [comment]
waarom is er een statische lijst nodig? is er iets mis met 

projectmanager -> loop projects -> loop tasks -> check if task is available

om available tasks op te halen?

**Comment by isostorm** [comment]
Nee, eigenlijk niet, kad gezien dat da ook zo gebeurt met jframes en da zag der wel proper uit. Maar ge moet per taak ook lik nog het project meegeven en da vind ik wat vreemd. Hier past dus ook beter een bidirectionele relatie, ge moet maar ne keer kijken hoe het nu gedaan wordt in de showprojecthandler, de GUI werkt trouwens al om dingen te bekijken.

**Comment by mrTsjolder** [comment]
het gaat niet over simele implementatie, maar een duurzaam design. Die bidirectionele dingen mogen er echt niet in als het gewoon niet anders gaat

**Comment by isostorm** [comment]
Ma is alles in een lijst pompen in de handler wel een goed design?

**Comment by mrTsjolder** [comment]
da zou normaal in de projectmanager of zelfs in project moeten gebeuren.

**Comment by isostorm** [comment]
Gebt gelijk der moet een methode getAllAvailableTasks in projectmanager. Ma dan moeje nog altijd op 1 of andere manier het project da bij de taak hoort meegeven zijn tuples dan de goeie manier

**Comment by mrTsjolder** [comment]
Ik dacht dat we daarvoor maps zouden gebruiken met de tasks als key...

**Comment by isostorm** [comment]
en dan als value hun project?

**Comment by mrTsjolder** [comment]
project of projectDetails, ik weet het allemaal eventjes niet meer wat best teruggaat :p
