### ISSUE TITLE
Opkuisen ontwerp

### ISSUE THREAD

**Issue by mrTsjolder** [mrTsjolder/SWOP-KULAK#8]
Ik heb het gevoel dat ons ontwerp een beetje random aan het worden is
We moeten echt goed nadenken over mogelijke alternatieven, want momenteel heb ik het gevoel dat onze koppeling alleen achteruit gaat en dat Task een beetje incohesive wordt.

PS: ik heb net hoofdstuk 8 gelezen en ik heb het gevoel dat ProjectManager eigenlijk gewoon een facade controller zou kunnen worden...

**Comment by isostorm** [comment]
Klopt, maar we hebben nu toch gekozen voor usecase handlers, het is ofwel het 1 of het ander hé?

**Comment by Xenolel** [comment]
ik heb ook het gevoel dat task te veel moet doen. heb je voorbeelden van dingen die momenteel in task gebeuren die daar niet echt horen?

**Comment by isostorm** [comment]
Der is lik nie echt iets da weg kan alsk ne keer rap kijk, ma zo groot is die klasse nu ook weer niet, vergeet nie da task de belangrijkste entiteit is van ons programma en 2 relaties met zichzelf heeft.

**Comment by mrTsjolder** [comment]
de dingen die te maken hebben met alternative tasks misschien naar project? Anders kan @Xenolel eens kijken of geen twee verschillende functionaliteiten onderscheiden kunnen worden. Hij kent de code het beste...

**Comment by mrTsjolder** [comment]
Om een idee te geven: 
![klassen](https://cloud.githubusercontent.com/assets/3738082/6506457/8418a12c-c34b-11e4-93cb-0f99a7e9c8b2.png)

**Comment by Xenolel** [comment]
Als je de koppeling tussen een task en zijn alternative task verbreekt, zou het project verantwoordelijk moeten zijn voor het checken op loops. Ook kan een task dan niet altijd zelf beslissen of zijn status ondertussen available is geworden en zou die verantwoordelijkheid dus ook moeten verplaatst worden.
vb:
A.status = available
C.prerequisite = A
A.status = failed
A.alternative = B (deze link zou dus worden bijgehouden in project)
B.status = finished
C.status = ? -> dit kan niet in Task beslist worden omdat A niet weet dat B zijn alternative task is

Daarom zouden we dit best niet doen denk ik?

**Comment by isostorm** [comment]
Pieter-Jan bedoelt wss dat er een methode setAlternativeTask(Tid, altTask) bestaat die eerst de check doet en dan de methode oproept op de taak met Tid? We weten niet zeker of die alternatieve taak niet tot een ander project mag behoren nog altijd.

**Comment by mrTsjolder** [comment]
Ik bedoelde inderdaad zoiets...
PS: kunnen die bi-directionele dingen niet opgelost worden door nog eens te kijken in welke richting alles bijgehouden wordt?

**Comment by Xenolel** [comment]
Wat gezegd is over alternative task geldt ook voor prerequisite tasks btw

Richting waarin dingen worden bijgehouden?
Project manager -> Projects
Project -> list of Tasks
Task -> alternative Task
Task -> list of prerequisite Tasks

Nu is de vraag, waar moet er gechecked worden of de prerequisite tasks en alternative task tot het juiste project horen

**Comment by mrTsjolder** [comment]
die dingen moeten sowieso in project gecheckt worden
Hij is de (enige) information expert
