### ISSUE TITLE
Addedum van de assignment

### ISSUE THREAD

**Issue by isostorm** [mrTsjolder/SWOP-KULAK#9]
Snapt iemand het addendum dat de prof toegevoegd heeft? : 
The assignment is not very clear about the role of the system time (as advanced by use case Advance Time). Therefore, we issue the following addendum to the assignment:

-For computing the estimated end time of a project (to be shown as part of use case Show Projects), assume that tasks that are past due (i.e., whose due date is in the past with respect to the current system time) end now, rather than at their due date.
-As part of use case Show Projects, for each task, show its status, as well as whether it is currently overdue, and by what percentage, and highlight tasks (e.g. using asterisks) that are unacceptably overdue.

**Comment by mrTsjolder** [comment]
ja: The addendum makes the assignment even less clear

**Comment by isostorm** [comment]
ja hebben taken een due time ofzo?

**Comment by mrTsjolder** [comment]
wat ik er van kan maken:
- taken die een eindtijd hebben in het verleden t.o.v. systeem tijd eindigen direct (moeten niet meer wachten tot ze finished zijn)
- voor elke taak die overtijd is, moet je kunnen zeggen hoeveel % ze al over tijd zijn op de systeemtijd van dat moment

**Comment by isostorm** [comment]
Maar de eind- en begintijd van een taak wordt toch pas gezet als ze finished of failed zijn?

**Comment by mrTsjolder** [comment]
het gaat over de estimated end time, dus moet je de duration van die taken eigenlijk bekijken...

**Comment by isostorm** [comment]
Punt 1 is opgelost: De estimated tijd van een project wordt op de huidige systeemtijd gezet, moest hij voor de huidige tijd vallen.

**Comment by isostorm** [comment]
Punt 2: We kunnen mogelijks kijken of een taak overdue is door te kijken naar de huidige systeemtijd en daarbij de estimated duration van de taak optellen en dan kijken hoeveel dit over de due time van het project gaat.

**Comment by isostorm** [comment]
Punt 2 kan opgelost worden door een lijst op te vragen aan project met de overdue taken.
